version: '3.9'

x-deploy: &deploy
  deploy:
    replicas: 1
    resources:
      limits:
        cpus: "0.8"
        memory: 200MB
    restart_policy:
      condition: on-failure
    placement:
      constraints:
        - node.role == worker


x-networks: &networks
  networks:
    - backend

networks:
  backend:
    name: framely


services:
  postgres:
    image: hdwhub/postgres:13
    volumes:
      - /mnt/nfs/apps/framely/pgdata:/var/lib/postgresql/data
      - /mnt/nfs/apps/framely/backups:/backups
    env_file:
      - /mnt/nfs/apps/framely/config/.postgres
    <<: *networks
    <<: *deploy

  user:
    image: hdwhub/framely-user-service:latest
    volumes:
      - /mnt/nfs/apps/framely/config/jwtkey:/usr/src/app/jwtkey:ro
      - /mnt/nfs/apps/framely/config/jwtkey.pub:/usr/src/app/jwtkey.pub:ro
      - /mnt/nfs/apps/framely/logs:/usr/src/app/logs:z
    env_file:
      - /mnt/nfs/apps/framely/config/user.env
    <<: *networks
    <<: *deploy
    ports:
      - 3025:3000
