version: '3.9'

x-deploy: &deploy
  deploy:
    replicas: 1
    resources:
      limits:
        cpus: "0.8"
        memory: 200MB
    restart_policy:
      condition: on-failure
    placement:
      constraints:
        - node.role == worker


x-networks: &networks
  networks:
    - backend

networks:
  backend:
    name: framely


services:
  creator:
    image: hdwhub/framely-creator-service:latest
    volumes:
      - /mnt/nfs/apps/framely/config/jwtkey.pub:/usr/src/app/jwtkey.pub:ro
      - /mnt/nfs/apps/framely/logs:/usr/src/app/logs:z
    env_file:
      - /mnt/nfs/apps/framely/config/creator.env
    <<: *networks
    <<: *deploy
    ports:
      - 3032:3000
